display_information:
  name: PaperBot
  description: Retrieves scientific papers
  background_color: "#595359"
features:
  bot_user:
    display_name: PaperBot
    always_online: false
  slash_commands:
    - command: /paperfind
      description: Retrieve scientific papers based on keyword search query
      usage_hint: query since
      should_escape: false
    - command: /paperlike
      description: Retrieve scientific papers similar to an existing paper
      usage_hint: title
      should_escape: false
    - command: /papercite
      description: Retrieve scientific papers citing this paper
      usage_hint: title
      should_escape: false
oauth_config:
  scopes:
    bot:
      - channels:history
      - chat:write
      - im:history
      - commands
settings:
  event_subscriptions:
    bot_events:
      - message.channels
      - message.im
  interactivity:
    is_enabled: true
  org_deploy_enabled: false
  socket_mode_enabled: true
  token_rotation_enabled: false
